import Link from "next/link";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen max-w-screen-md mx-auto font-mono px-2">
        <NextTopLoader />
        <Navbar />
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}

const Navbar = () => {
  return (
    <div className="py-2">
      <nav className="flex justify-between items-center">
        <h1 className="text-xl font-bold">
          <Link href="/">LibreReads</Link>
        </h1>
        <ul className="flex gap-3 items-center">
          <li>
            <Link href="/search/">Search</Link>
          </li>
          <li>
            <Link href="/search/">About</Link>
          </li>
        </ul>
      </nav>
    </div>
  );
};

const Footer = () => {
  return (
    <div className="text-center py-1">
      <a
        className="underline underline-offset-2"
        href="https://github.com/lmssiehdev/librereads"
      >
        source code
      </a>
    </div>
  );
};
